name: Merge-branch
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events
    # - cron:  '0 0-23 * * *' '*/15 * * * *'    
    - cron:  '*/15 * * * *'

jobs:
  merge:

    runs-on: ubuntu-latest

    steps:
    - uses: binodswain/merge-branch@master
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        base: "master"
        head: "develop"